models:
  llm_model: 'gpt-4.1'
  max_tokens: 4096
data:
  persona_path: 'data/Persona_Hub_200000.jsonl'
  conv_output_path: 'data/interactions.jsonl'
  result_path: 'results/'
  irrelevant_context_path: 'data/irrelevant_contexts.json'
  data_types: 'email'
inference:
  num_persona: 1
  verbose: False